name: "torch_model"
platform: "pytorch_libtorch"
max_batch_size: 1

input [
  {
    name: "%inputs"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, -1, -1]
    reshape {shape: [1, 3, -1, -1]}
  }
]

output [
  {
    name: "%6589"
    data_type: TYPE_FP32
    dims: [-1, 4]
  },
  {
    name: "%6540"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "%6542"
    data_type: TYPE_FP32
    dims: [-1]
  }
]
