name: "torch_model"
platform: "pytorch_libtorch"
max_batch_size: 0  # if model has no batch dimension, just set like this

input [
  {
    name: "inputs"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, -1, -1]
  }
]

output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [-1, 4]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "labels"
    data_type: TYPE_INT64
    dims: [-1]
  }
]
